/**
 * One-tap change-ticket briefing: the planned move as plain English.
 *
 * Deterministic templates over numbers the app already computed — nothing is
 * generated, so nothing can be wrong that the numbers aren't. The text is
 * built from the SAME derived states and plan the display surfaces use;
 * `test/briefing.test.js` pins that every number in the prose matches its
 * source input, so the sentence can never contradict the table beside it.
 */

/**
 * @param {object} p
 * @param {object} p.a        deriveStateF result for Current
 * @param {object} p.b        deriveStateF result for Target
 * @param {object} p.plan     planMove()-shaped: {hours, binding, moistCap}
 * @param {{name?:string,siteName?:string,elevFt?:number}} p.hall
 * @param {{name?:string}|null} p.sla
 * @param {{aOk:boolean,bOk:boolean,aDetail?:string,bDetail?:string}} p.verdicts
 * @param {(f:number)=>string} p.fmtT   absolute °F → display-unit string incl. label
 * @param {(fDelta:number)=>string} p.fmtDT temperature DELTA °F → display string incl. label
 *   (a delta is not an absolute: +9 °F is +5 °C and +5 K, never +278 K)
 * @param {(hrs:number)=>string} p.fmtHrs
 * @param {{tempF:number, rh:number}[]} [p.hourly] optional hour-by-hour
 *   set-point ladder, computed by the CALLER with the same interpolation the
 *   chart's pacing ticks use — the briefing only narrates, never re-derives
 * @param {Date} [p.generatedAt] timestamp for the footer, passed in by the
 *   caller so the text stays a pure function of its inputs (and testable)
 * @returns {string}
 */
export function buildBriefing(p) {
  const { a, b, plan, hall, sla, verdicts, fmtT, fmtDT, fmtHrs, hourly, generatedAt } = p;
  const dT = b.tempF - a.tempF;
  const dRH = b.rh - a.rh;
  const dDp = b.tdpF != null && a.tdpF != null ? b.tdpF - a.tdpF : null;
  const dir =
    dT > 0.05 ? 'Warm' : dT < -0.05 ? 'Cool' : dRH > 0.05 ? 'Humidify' : dRH < -0.05 ? 'Dehumidify' : 'Hold';

  const lines = [];
  const where = [hall?.name, hall?.siteName].filter(Boolean).join(' · ');
  lines.push(
    `${dir} ${where || 'the hall'}: ${fmtT(a.tempF)} / ${a.rh.toFixed(0)}% RH → ${fmtT(b.tempF)} / ${b.rh.toFixed(0)}% RH.`,
  );

  const deltas = [];
  if (Math.abs(dT) > 0.05) deltas.push(`ΔT ${dT > 0 ? '+' : '−'}${fmtDT(Math.abs(dT))}`);
  if (Math.abs(dRH) > 0.05) deltas.push(`ΔRH ${dRH > 0 ? '+' : '−'}${Math.abs(dRH).toFixed(0)}%`);
  if (dDp != null)
    deltas.push(
      Math.abs(dDp) < 0.3
        ? 'dew point unchanged'
        : `dew point ${dDp > 0 ? 'rises' : 'falls'} ${fmtDT(Math.abs(dDp))}`,
    );
  deltas.push(`W ${a.Wg.toFixed(2)} → ${b.Wg.toFixed(2)} g/kg`);
  lines.push(deltas.join(' · ') + '.');

  if (plan && plan.hours > 0) {
    lines.push(`Estimated duration ≥ ${fmtHrs(plan.hours)} — binding constraint: ${plan.binding}.`);
    if (plan.moistCap)
      // Direction comes from the plan's own label (`Dehum`/`Humidify`), the
      // same field the on-screen readout branches on. `waterLb` is a MASS —
      // always positive — so a sign test on it once briefed every
      // humidification move as "moisture to remove".
      lines.push(
        `Moisture to ${plan.moistCap.label === 'Dehum' ? 'remove' : 'add'}: ${Math.abs(plan.moistCap.waterLb).toFixed(0)} lb of water.`,
      );
  } else if (plan && (plan.needsTempRate || plan.needsVol)) {
    lines.push('Duration unknown — plant rates are not set for this hall.');
  } else if (plan) {
    lines.push('No plant work required — the points differ only within rounding.');
  }

  // Hour-by-hour ladder: what the hall should read at each top of the hour if
  // the move paces evenly — the same points the chart's pacing ticks mark.
  if (Array.isArray(hourly) && hourly.length) {
    lines.push('Hourly set-points:');
    hourly.forEach((pt, i) => {
      const last = i === hourly.length - 1;
      lines.push(`  Hour ${i + 1}${last ? ' (arrival)' : ''}: ${fmtT(pt.tempF)} / ${pt.rh.toFixed(0)}% RH`);
    });
  }

  const slaName = sla?.name ? ` (${sla.name})` : '';
  if (verdicts) {
    if (verdicts.aOk && verdicts.bOk) lines.push(`Both points inside SLA${slaName}.`);
    else {
      if (!verdicts.aOk) lines.push(`Current is OUTSIDE SLA${slaName}: ${verdicts.aDetail || 'bound violated'}.`);
      if (!verdicts.bOk) lines.push(`Target is OUTSIDE SLA${slaName}: ${verdicts.bDetail || 'bound violated'}.`);
    }
  }

  if (hall?.elevFt != null) lines.push(`Site pressure basis: ${Math.round(hall.elevFt).toLocaleString()} ft elevation (standard atmosphere — weather swings ±2 kPa).`);
  const stamp = generatedAt instanceof Date && isFinite(generatedAt.getTime())
    ? `Generated ${generatedAt.toISOString().slice(0, 16).replace('T', ' ')} UTC by Hall Environment Planner`
    : 'Generated by Hall Environment Planner';
  lines.push(`${stamp} — verify against site instrumentation before acting.`);
  return lines.join('\n');

}
